# mini-server — build rules
#
#   make          build everything into bin/
#   make clean    remove build/ and bin/
#
# Object files and binaries never land next to the sources.

CC       ?= cc
CFLAGS   ?= -std=c11 -Wall -Wextra -Wpedantic -O2 -pthread
LDFLAGS  ?= -pthread

SRC_DIR   := src
INC_DIR   := includes
BUILD_DIR := build
BIN_DIR   := bin

CPPFLAGS ?= -I$(INC_DIR) -MMD -MP

# net_util is linked into both servers but not into the client.
COMMON_OBJ := $(BUILD_DIR)/net_util.o

PROGRAMS := server_unsafe server_safe load_client
BINARIES := $(addprefix $(BIN_DIR)/,$(PROGRAMS))

.PHONY: all clean

all: $(BINARIES)

$(BIN_DIR)/server_unsafe: $(BUILD_DIR)/server_unsafe.o $(COMMON_OBJ) | $(BIN_DIR)
	$(CC) $(LDFLAGS) -o $@ $^

$(BIN_DIR)/server_safe: $(BUILD_DIR)/server_safe.o $(COMMON_OBJ) | $(BIN_DIR)
	$(CC) $(LDFLAGS) -o $@ $^

$(BIN_DIR)/load_client: $(BUILD_DIR)/load_client.o | $(BIN_DIR)
	$(CC) $(LDFLAGS) -o $@ $^

$(BUILD_DIR)/%.o: $(SRC_DIR)/%.c | $(BUILD_DIR)
	$(CC) $(CFLAGS) $(CPPFLAGS) -c -o $@ $<

$(BUILD_DIR) $(BIN_DIR):
	mkdir -p $@

clean:
	rm -rf $(BUILD_DIR) $(BIN_DIR)

# Header dependencies generated by -MMD -MP: touching net_util.h rebuilds
# every object that includes it.
-include $(wildcard $(BUILD_DIR)/*.d)
